---
- name: set password user 
  hosts: vm_server 
  gather_facts: yes 


  tasks: 
   - name: to set password 
     user: 
      name: nick
      update_password: always
      password: "{{'abcd12345' | password_hash('sha512', 'mysecretcode')}}"