---
- name: Install and start the services
  hosts: vm_server
  gather_facts: yes
  become: yes
  vars:
    - app: httpd

  tasks:
    - name: Installing nginx
      apt:
        name: "{{ app }}"
        state: present
      tags: i-nginx  

    - name: Starting the Nginx service
      service:
        name: "{{ app }}"
        state: started
        enabled: true
      tags: ss-nginx   